engines:
  gnu-complexity:
    enabled: true
    config:
      threshold: 100
  markdownlint:
    enabled: true
  fixme:
    enabled: true
exclude_paths:
- docs/**/*

ratings:
  paths:
  - "**.md"
  - "./src/**/*"
